# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkcve',
            fields=[
                ('probe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Probe')),
            ],
            bases=('home.probe',),
        ),
        migrations.CreateModel(
            name='Cve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=700)),
                ('cpe', models.CharField(max_length=100)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.OsSupported')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cves', select2.fields.ManyToManyField(blank=True, help_text=None, sort_value_field_name='name', to='checkcve.Cve')),
            ],
        ),
        migrations.AddField(
            model_name='checkcve',
            name='softwares',
            field=models.ManyToManyField(blank=True, to='checkcve.Software'),
        ),
        migrations.AddField(
            model_name='checkcve',
            name='whitelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkcve.WhiteList'),
        ),
        migrations.AlterUniqueTogether(
            name='software',
            unique_together=set([('name', 'os')]),
        ),
    ]
